---
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    password: !secret ap_password
    ssid: "${friendly_name}: Fallback Hotspot"

sensor:
  - platform: wifi_signal
    name: "${friendly_name}: WiFi Signal"
    update_interval: 60s
    id: wifi_signal_sensor
