---
substitutions:
  board: esp01_1m

esp8266:
  board: ${board}
  restore_from_flash: true

packages:
  base: !include common-base.yaml
  wifi: !include common/wifi.yaml
  web_server: !include common/webserver.yaml
  captive_portal: !include common/captive_portal.yaml
