---
esphome:
  name: ${name}
  friendly_name: ${friendly_name}

packages:
  api: !include common/api.yaml
  binary_sensors: !include common/binary_sensors.yaml
  buttons: !include common/buttons.yaml
  logger: !include common/logger.yaml
  ota: !include common/ota.yaml
  sensors: !include common/sensors.yaml
  time: !include common/time.yaml
